-- Expolatory Data Analysis

-- 1. Database Exploration

-- Explore all objects from the database tables
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore the columns from the database tables
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'gold';

-- 2. Dimention Exploration

-- Explore all the countries our customers came from
SELECT DISTINCT country FROM gold.dim_customers

-- Explore all the moajor categories of products
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_product
ORDER BY 1,2,3


-- 3. Date Exploration

-- First and last order
SELECT
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- Customer birthdate analysis
SELECT 
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(year,MIN(birthdate),GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers


-- 4. Measure Exploration

-- Find the total sales
SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales;

-- Find how many items are sold
SELECT COUNT(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the total number of Orders
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(DISTINCT product_id) AS total_products FROM gold.dim_product

-- Find the total number of customers
SELECT COUNT(DISTINCT customer_id) AS total_customers FROM gold.dim_customers

-- Find the total number of cutomers that has placed an order
SELECT COUNT(DISTINCT customer_id) AS ordered_customer_count FROM gold.fact_sales

-- Generate A Report that show all metrics of the business

SELECT 'Total_Sales' AS measure_name , SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'total_quantity' AS measure_name , COUNT(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'avg_price' AS measure_name , AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'total_orders' AS measure_name , COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'total_products' AS measure_name , COUNT(DISTINCT product_id) AS measure_value FROM gold.dim_product
UNION ALL
SELECT 'total_customers' AS measure_name , COUNT(DISTINCT customer_id) AS measure_value FROM gold.dim_customers;


-- 5. Magnitude Analyis
-- Aggregate [Measure] By [Dimension]

-- Find total customers by countries
SELECT 
	COUNT(customer_id)AS total_customers,
	country
FROM gold.dim_customers
GROUP BY country

-- Find total customers by gender
SELECT 
	COUNT(customer_id)AS total_customers,
	gender
FROM gold.dim_customers
GROUP BY gender

--Find total products by category
SELECT 
	COUNT(category)AS total_customers,
	category
FROM gold.dim_product
GROUP BY category

-- Avg cost in each category
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_product
GROUP BY category

-- Total revenue generated by each category
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
left JOIN gold.dim_product p
ON f.product_number = p.product_number
GROUP BY p.category
ORDER BY total_revenue DESC

-- Total revenue generated by each customer
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
left JOIN gold.dim_customers c
ON f.customer_id = c.customer_id
GROUP BY c.customer_id,c.first_name,c.last_name
ORDER BY total_revenue DESC

-- Distribution of sold items across countries
SELECT
	c.country,
	COUNT(f.order_number) AS total_orders
FROM gold.fact_sales f
left JOIN gold.dim_customers c
ON f.customer_id = c.customer_id
GROUP BY c.country
ORDER BY total_orders DESC


-- 6. Ranking Analysis
-- Rank[Dimension] by [Measure]

-- 5 products with highest revenue
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
left JOIN gold.dim_product p
ON f.product_number = p.product_number
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- 5 worst performing products in sales
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
left JOIN gold.dim_product p
ON f.product_number = p.product_number
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- Top 10 customers who have highest revenue
SELECT *
FROM (
	SELECT
		c.customer_id,
		SUM(f.sales_amount) AS total_revenue,
		RANK() OVER(ORDER BY SUM(f.sales_amount) DESC) ra
	FROM gold.fact_sales f
	left JOIN gold.dim_customers c
	ON f.customer_id = c.customer_id
	GROUP BY c.customer_id) t
WHERE ra <= 10; 

-- 3 customer with fewest orders placed
SELECT *
FROM (
	SELECT
		c.customer_id,
		COUNT(f.order_number) AS total_orders,
		RANK() OVER(ORDER BY COUNT(f.order_number)) ra
	FROM gold.fact_sales f
	left JOIN gold.dim_customers c
	ON f.customer_id = c.customer_id
	GROUP BY c.customer_id) t
WHERE ra <= 5; 

SELECT * FROM gold.fact_sales
SELECT * FROM gold.dim_product
SELECT * FROM gold.dim_customers
